### ISSUE TITLE
Cannot read property 'length' of undefined. api_blueprint to swagger_2

### ISSUE THREAD

**Issue by dobromir-bogatev** [LucyBot-Inc/api-spec-converter#133]
Im getting the following error while trying to convert from api_blueprint to swagger_2
`Fatal TypeError: Cannot read property 'length' of undefined
    at jsonSchemaFromMSON (/usr/local/lib/node_modules/api-spec-converter/node_modules/apib2swagger/index.js:217:37)
    at /usr/local/lib/node_modules/api-spec-converter/node_modules/apib2swagger/index.js:38:67
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/api-spec-converter/node_modules/apib2swagger/index.js:31:26
    at Array.forEach (<anonymous>)
    at Object.module.exports.convertParsed (/usr/local/lib/node_modules/api-spec-converter/node_modules/apib2swagger/index.js:28:8)
    at converters.swagger_2.Promise.method.apibp (/usr/local/lib/node_modules/api-spec-converter/lib/formats/api_blueprint.js:16:24)
    at tryCatcher (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/util.js:16:23)
    at /usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/method.js:15:34
    at Promise.try (/usr/local/lib/node_modules/api-spec-converter/lib/base_format.js:162:12)
    at tryCatcher (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/method.js:39:29)
    at module.exports.BaseFormat.convertTo (/usr/local/lib/node_modules/api-spec-converter/lib/base_format.js:154:21)
    at Converter.getSpec.then.fromSpec (/usr/local/lib/node_modules/api-spec-converter/index.js:33:32)
    at tryCatcher (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:512:31)`

**Comment by MikeRalphson** [comment]
Can you post a link to your definition? As per the stacktrace above, it's causing an error in one of our dependencies [apib2swagger](https://github.com/kminami/apib2swagger).

**Comment by dobromir-bogatev** [comment]
I am not really familiar with these documentation formats. Do you need me to post the whole document I am trying to covert or just this part:
`### Definitions
**Customer**
**Claim**
**File**
**Payment**
**Refund**
**Message**
**Document**
**Event**
**Account**
**Statement**`

**Comment by MikeRalphson** [comment]
If you could post (ideally a link to, or a gist of) the whole document I could test the fix proposed above, and then one of us could raise an issue on the apib2swagger to get it fixed properly. It's also possible your .apib file is non-standard in some way.

Please feel free to email if it is confidential (email on profile page).

**Comment by dobromir-bogatev** [comment]
It is public documentation for the API of the company I work at so I think it is not confidential.
https://github.com/eCollect/docs/blob/master/apiary.apib

**Comment by MikeRalphson** [comment]
That link 404s for me, so I guess it isn't a public repository. Is the apib file hosted anywhere else?

**Comment by dobromir-bogatev** [comment]
Sorry, the repository is not public as i thought.

Here is a gist:

https://gist.github.com/dobromir-bogatev/7ab8de885c1433764ba575dc9cf64a2b

**Comment by MikeRalphson** [comment]
Reproduced.

**Comment by MikeRalphson** [comment]
With my proposed fix I'm able to convert the definition. I've put a copy [here](https://gist.github.com/MikeRalphson/7c9339ab4332e61b9091fcd308b1da7b) for reference.

When validating the resultant Swagger 2.0 definition, there are a few errors which will need looking at:-

* there are `$ref`s to `#/definitions/object` which doesn't exist, these can probably be changed to just `type: object`, and might be the result of syntax errors in your source API Blueprint definition
* apib2swagger has not converted correctly the `in: query` parameters, so the `paths` have ?s in them. This can be corrected by removing everything following the ? and changing the `in: path` parameters to `in: query` where required.
* apib2swagger has left several empty `required: []` arrays - these need removing
* apib2swagger has set several properties to `type: enum` instead of a primitive type with an `enum: []` array
* apib2swagger has set some property `type`s to schema names (`CUSTOMER_RESPONSE`, `STATUS_RESPONSE`)

[Updating...]

**Comment by dobromir-bogatev** [comment]
Im sorry I didn't answer here for a while. We passed the document through a validator and cleared up the errors. Thank you for all your help.

**Comment by bobby-brennan** [comment]
Thanks for following up!
