### ISSUE TITLE
Not support from openapi_3 to swagger_2

### ISSUE THREAD

**Issue by shenghu** [LucyBot-Inc/api-spec-converter#134]
From readme, it says to support. But I got this error, 

```
Fatal Error: Unable to convert from openapi_3 to swagger_2
    at Promise.try (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/lib/base_format.js:160:13)
    at tryCatcher (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/method.js:39:29)
    at module.exports.BaseFormat.convertTo (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/lib/base_format.js:154:21)
    at Converter.getSpec.then.fromSpec (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/index.js:33:32)
    at tryCatcher (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/shenghu/.nvm/versions/node/v7.8.0/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

Is there anything I missing?

**Comment by MikeRalphson** [comment]
I'm sorry, that is a copy-and-paste error in the README. It would not be possible to convert an openapi_3 definition to swagger_2 easily, as information would be lost in several areas and some features are completely unsupported.

**Comment by MikeRalphson** [comment]
For a one-off conversion you could try https://apimatic.io/transformer but I'd suspect the output would need hand-editing.

**Comment by MikeRalphson** [comment]
I have raised a PR #135 to update the README - thanks for pointing it out!

Probably your best option is to convert the Swagger 2.0 definition to OpenAPI 3.0 and compare those? You could use api-spec-converter for the conversion in this direction.

**Comment by shenghu** [comment]
@MikeRalphson thanks. I'll watch openapi-diff.

**Comment by bobby-brennan** [comment]
Closing this for now since it's fixed in the README. Converting 3 => 2 (lossily ofc) is something we'll consider down the line though.
