### ISSUE TITLE
Command line tool : TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by milanbr** [LucyBot-Inc/api-spec-converter#148]
When run:

api-spec-converter pisp.apib --from=api_blueprint --to=swagger_2 > swagger.json

I get:

```
node_modules\api-spec-converter\node_modules\drafter.js\lib\drafter.nomem.js:1
(function (exports, require, module, __filename, __dirname) { ((function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(
typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.drafter=f()}}))((function(){var module;var Module;if(!Module){Module={}}Module["ready"]=f
alse;Module["log"]=(function(text){console.log("drafter.js: "+text)});Module["logErr"]=(function(text){console.error("drafter.js: "+text)});Module["onRuntimeInitialized"]=(function(){this.ready=true});var Module;if(!Module)Module
=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false

TypeError: Cannot read property 'call' of undefined
    at CompositeError.get (C:\Users\cen76482\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\composite-error\lib\compositeError.js:45:50)
    at CompositeError.formatStackTraces (C:\Users\cen76482\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\composite-error\lib\compositeError.js:56:23)
    at CompositeError.get (C:\Users\cen76482\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\composite-error\lib\compositeError.js:25:39)
    at Async.fatalError (C:\Users\cen76482\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\async.js:50:65)
    at Promise._reject (C:\Users\cen76482\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\promise.js:652:22)
    at Promise._settlePromise (C:\Users\cen76482\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\promise.js:584:21)
    at Promise._settlePromise0 (C:\Users\cen76482\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\cen76482\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\cen76482\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\cen76482\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\cen76482\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\async.js:17:14)

```

**Comment by bobby-brennan** [comment]
Can you share your apibp file? The command works for me with this one:

https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/Polls%20API.md

**Comment by mieszkomalawski** [comment]
Same here, when converting from openapi_3 to swagger_2

**Comment by canvural** [comment]
Same happens to me. From `api_blueprint` to `openapi_3`

**Comment by mieszkomalawski** [comment]
Unfortunately I cannot share because definition contains company internal APIs, maybe @milanbr or @canvural  can?

**Comment by janpieper** [comment]
```

**Comment by bobby-brennan** [comment]
Thanks for the details!

Unfortunately I wasn't able to trigger the error by setting a query parameter to `integer` - any more details you can share on how to reproduce?

**Comment by gunters63** [comment]
I had the same problem and added another line in bluebirds promise.js (line 658) to track the problem down:

` console.log(JSON.stringify(reason, null, 4));`

This is the error message I got:

````
{
    "name": "CompositeError",
    "message": "Failed to parse spec",
    "innerErrors": [
        {
            "result": {
                "_version": "2.2",
                "error": {
                    "code": 2,
                    "message": "the use of carriage return(s) '\\r' in source data isn't currently supported, please contact makers",
                    "location": [
                        {
                            "index": 1087,
                            "length": 1
                        }
                    ]
                },
                "warnings": []
            }
        }
    ],
````

After a change all line-endings to LF (unix) the converter worked

**Comment by peterhut** [comment]
Encountered the same issue trying to convert the apibp file downloaded from https://gost1.docs.apiary.io/
[gost1.apib.txt](https://github.com/LucyBot-Inc/api-spec-converter/files/3534274/gost1.apib.txt)

**Comment by blazekv** [comment]
I had same problem as @gunters63 . File was saved with CRLF. Saving file as Unix style solves the problem.

@rbren IMHO It will be sufficient to handle error message and raise more specific message. Original error message is really confusing.
