### ISSUE TITLE
Converting from API Blueprint to Open API 3 Fails with "Fatal TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by jakejgordon** [LucyBot-Inc/api-spec-converter#156]
I'm attempting to convert from API Blueprint to Open API 3 via the following command:

```api-spec-converter https://github.com/NemeStats/NemeStats/blob/master/apiary.apib --from=api_blueprint --to=openapi_3 > nemestats_openapi3.json```

This yields the following error:
```
Fatal TypeError: Cannot read property 'length' of undefined
    at jsonSchemaFromMSON (C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\apib2swagger\index.js:266:38)
    at C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\apib2swagger\index.js:39:67
    at Array.forEach (<anonymous>)
    at C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\apib2swagger\index.js:32:26
    at Array.forEach (<anonymous>)
    at Object.module.exports.convertParsed (C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\apib2swagger\index.js:29:8)
    at converters.swagger_2.Promise.method.apibp (C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\lib\formats\api_blueprint.js:16:24)
    at tryCatcher (C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\method.js:15:34
    at Promise.try (C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\lib\base_format.js:162:12)
    at tryCatcher (C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\method.js:39:29)
    at module.exports.BaseFormat.convertTo (C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\lib\base_format.js:154:21)
    at prom.then.spec (C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\lib\base_format.js:178:19)
    at tryCatcher (C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\jakejgordon\AppData\Roaming\npm\node_modules\api-spec-converter\node_modules\bluebird\js\release\promise.js:512:31)
```

Please let me know if there is any other information I can provide. (and thanks for making this openly available!)

**Comment by bobby-brennan** [comment]
Are you on the latest version?

```bash
api-spec-converter --version
2.7.1
```

That command works fine for me on Ubuntu.

**Comment by bobby-brennan** [comment]
Closing due to inactivity - feel free to reopen with more info
