### ISSUE TITLE
External references do not work. 

### ISSUE THREAD

**Issue by kappj** [LucyBot-Inc/api-spec-converter#163]
All of my schemas are in separate files. It would be awesome if an external reference to these schemas in my OAS 3 spec could be resolved by the converter. 

Ex:
```
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "./schemas/file/path/to/schema.json"
                }
              }
            }
          }
        }
```

Converting the above currently doesn't work and fails with the following:

```
Fatal TypeError: Cannot read property 'fieldInfo' of undefined
    at /Users/jdkapp/.config/yarn/global/node_modules/api-spec-converter/lib/converters/openapi3_to_swagger2.js:63:39
    at Array.forEach (<anonymous>)
    at resolveReference (/Users/jdkapp/.config/yarn/global/node_modules/api-spec-converter/lib/converters/openapi3_to_swagger2.js:63:8)
    at convertResponses (/Users/jdkapp/.config/yarn/global/node_modules/api-spec-converter/lib/converters/openapi3_to_swagger2.js:198:24)
    at convertOperations (/Users/jdkapp/.config/yarn/global/node_modules/api-spec-converter/lib/converters/openapi3_to_swagger2.js:92:17)
    at convert (/Users/jdkapp/.config/yarn/global/node_modules/api-spec-converter/lib/converters/openapi3_to_swagger2.js:24:3)
    at converters.swagger_2.Promise.method.oa (/Users/jdkapp/.config/yarn/global/node_modules/api-spec-converter/lib/formats/openapi_3.js:17:26)
    at tryCatcher (/Users/jdkapp/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/jdkapp/.config/yarn/global/node_modules/bluebird/js/release/method.js:15:34
    at Promise.try (/Users/jdkapp/.config/yarn/global/node_modules/api-spec-converter/lib/base_format.js:162:12)
    at tryCatcher (/Users/jdkapp/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/jdkapp/.config/yarn/global/node_modules/bluebird/js/release/method.js:39:29)
    at module.exports.BaseFormat.convertTo (/Users/jdkapp/.config/yarn/global/node_modules/api-spec-converter/lib/base_format.js:154:21)
    at Converter.getSpec.then.fromSpec (/Users/jdkapp/.config/yarn/global/node_modules/api-spec-converter/index.js:33:32)
    at tryCatcher (/Users/jdkapp/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jdkapp/.config/yarn/global/node_modules/bluebird/js/release/promise.js:512:31)
```

**Comment by bobby-brennan** [comment]
I believe this was fixed in 2.7.12 - let me know if you see otherwise.
