### ISSUE TITLE
how to resolve this error

### ISSUE THREAD

**Issue by shahzaibijaz** [LucyBot-Inc/api-spec-converter#169]
How to resolve this error plz help me its urgent

error: Can't set headers after they are sent.
   at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
   at ServerResponse.header (F:\project fyp\node_modules\express\lib\response.js:767:10)
   at ServerResponse.send (F:\project fyp\node_modules\express\lib\response.js:170:12)
   at F:\project fyp\app.js:126:6
   at Layer.handle [as handle_request] (F:\project fyp\node_modules\express\lib\router\layer.js:95:
)
   at next (F:\project fyp\node_modules\express\lib\router\route.js:137:13)
   at Route.dispatch (F:\project fyp\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (F:\project fyp\node_modules\express\lib\router\layer.js:95:
)
   at F:\project fyp\node_modules\express\lib\router\index.js:281:22
   at Function.process_params (F:\project fyp\node_modules\express\lib\router\index.js:335:12)

**Comment by bobby-brennan** [comment]
This doesn't look like it has anything to do with `api-spec-converter`, sorry.

I think your problem is with `express`. You're probably calling `res.send()` twice.
