### ISSUE TITLE
unable to install commandline tool

### ISSUE THREAD

**Issue by zhemant** [LucyBot-Inc/api-spec-converter#187]
```
78297 warn optional Skipping failed optional dependency /chokidar/fsevents:
78298 warn notsup Not compatible with your operating system or architecture: fsevents@1.2.4
78299 verbose stack Error: puppeteer@1.9.0 install: `node install.js`
78299 verbose stack spawn ENOENT
78299 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
78299 verbose stack     at emitTwo (events.js:87:13)
78299 verbose stack     at ChildProcess.emit (events.js:172:7)
78299 verbose stack     at maybeClose (internal/child_process.js:821:16)
78299 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
78300 verbose pkgid puppeteer@1.9.0
78301 verbose cwd /opt/api-spec-converter
78302 error Linux 4.15.0-36-generic
78303 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
78304 error node v4.2.6
78305 error npm  v3.5.2
78306 error file sh
78307 error code ELIFECYCLE
78308 error errno ENOENT
78309 error syscall spawn
78310 error puppeteer@1.9.0 install: `node install.js`
78310 error spawn ENOENT
78311 error Failed at the puppeteer@1.9.0 install script 'node install.js'.
78311 error Make sure you have the latest version of node.js and npm installed.
78311 error If you do, this is most likely a problem with the puppeteer package,
78311 error not with npm itself.
78311 error Tell the author that this fails on your system:
78311 error     node install.js
78311 error You can get information on how to open an issue for this project with:
78311 error     npm bugs puppeteer
78311 error Or if that isn't available, you can get their info via:
78311 error     npm owner ls puppeteer
78311 error There is likely additional logging output above.
78312 verbose exit [ 1, true ]
```

Any help on how to resolve this issue. I installed latest npm, nodejs.

**Comment by zhemant** [comment]
Was able to solve the issue after installing nodejs-legacy.
