### ISSUE TITLE
Error converting Google discover to swagger 2

### ISSUE THREAD

**Issue by swbuehler** [LucyBot-Inc/api-spec-converter#196]
```
steven@Alienware15R3:/mnt/d/Users/steve/Downloads$ api-spec-converter -f google -t swagger_2 "https://photoslibrary.googleapis.com/$discovery/rest?version=v1" > photoslibrary.google.com.json
Fatal Error: Can not GET https://photoslibrary.googleapis.com//rest?version=v1: Not Found
    at Request.spread (/usr/local/lib/node_modules/api-spec-converter/lib/util.js:33:15)
    at tryCatcher (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:638:18)
    at Request._callback (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/nodeback.js:45:21)
```

**Comment by bobby-brennan** [comment]
Hi Steven,

The error says it all - that URL returns a 404:

[https://photoslibrary.googleapis.com//rest?version=v1](https://photoslibrary.googleapis.com//rest?version=v1)

**Comment by bobby-brennan** [comment]
It looks like you wanted the literal URL, `https://photoslibrary.googleapis.com/$discovery/rest?version=v1`. You need to escape the `$` in bash, so:

```
api-spec-converter -f google -t swagger_2 "https://photoslibrary.googleapis.com/\$discovery/rest?version=v1"
```
