### ISSUE TITLE
OAS3 -> Swagger 2: TypeError: Formats[format] is not a constructor

### ISSUE THREAD

**Issue by seetamraju** [LucyBot-Inc/api-spec-converter#203]
api-spec-converter --from=swagger_3 --to=swagger_2 --syntax=yaml --order=alpha https://api.swaggerhub.com/apis/org.ASUX.playground/SwaggerHub-OAS3.0-PetStore/1.0.0

On MacOS (tried the website to convert, but it just hung).

/usr/local/lib/node_modules/api-spec-converter/node_modules/drafter.js/lib/drafter.nomem.js:1
(function (exports, require, module, __filename, __dirname) { ((function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.drafter=f()}}))((function(){var module;var Module;if(!Module){Module={}}Module["ready"]=false;Module["log"]=(function(text){console.log("drafter.js: "+text)});Module["logErr"]=(function(text){console.error("drafter.js: "+text)});Module["onRuntimeInitialized"]=(function(){this.ready=true});var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NOD

TypeError: Formats[format] is not a constructor
    at Object.Converter.getSpec (/usr/local/lib/node_modules/api-spec-converter/index.js:15:14)
    at Object.Converter.convert (/usr/local/lib/node_modules/api-spec-converter/index.js:32:20)
    at Command.main (/usr/local/lib/node_modules/api-spec-converter/bin/api-spec-converter:33:13)
    at Command.listener (/usr/local/lib/node_modules/api-spec-converter/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/api-spec-converter/node_modules/commander/index.js:656:12)
    at Command.parse (/usr/local/lib/node_modules/api-spec-converter/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/api-spec-converter/bin/api-spec-converter:24:4)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

**Comment by MikeRalphson** [comment]
Try `--from=openapi_3`
