### ISSUE TITLE
Fatal TypeError: Error during conversion: oldType.trim is not a function

### ISSUE THREAD

**Issue by ianfixes** [LucyBot-Inc/api-spec-converter#212]
I'm using this library for the first time, version `2.8.3`.  I'm attempting to convert `https://api.newrelic.com/v2/definitions.json` from Swagger 1.1 to 2 (or higher, but I see that conversion to 2.0 is the first step in that process).

Steps to reproduce:

```shell
$ npm install -s api-spec-converter
/home/me/newrelic
└── api-spec-converter@2.8.3 

$ ./node_modules/.bin/api-spec-converter -f swagger_1 -t swagger_2 -s json https://api.newrelic.com/v2/definitions.json 
Fatal TypeError: Error during conversion: oldType.trim is not a function
    at Converter.prototype.buildTypeProperties (/home/me/newrelic/node_modules/swagger-converter/index.js:340:21)
    at Converter.prototype.buildDataType (/home/me/newrelic/node_modules/swagger-converter/index.js:430:21)
    at Converter.prototype.buildModel (/home/me/newrelic/node_modules/swagger-converter/index.js:760:22)
    at Converter.prototype.buildModel (/home/me/newrelic/node_modules/swagger-converter/index.js:757:18)
    at Converter.<anonymous> (/home/me/newrelic/node_modules/swagger-converter/index.js:749:37)
    at /home/me/newrelic/node_modules/swagger-converter/index.js:842:7
    at Array.forEach (native)
    at Converter.prototype.forEach (/home/me/newrelic/node_modules/swagger-converter/index.js:841:36)
    at Converter.prototype.buildModel (/home/me/newrelic/node_modules/swagger-converter/index.js:744:8)
    at Converter.<anonymous> (/home/me/newrelic/node_modules/swagger-converter/index.js:782:28)
    at /home/me/newrelic/node_modules/swagger-converter/index.js:842:7
    at Array.forEach (native)
    at Converter.prototype.forEach (/home/me/newrelic/node_modules/swagger-converter/index.js:841:36)
    at Converter.prototype.buildDefinitions (/home/me/newrelic/node_modules/swagger-converter/index.js:781:8)
    at Converter.<anonymous> (/home/me/newrelic/node_modules/swagger-converter/index.js:142:30)
    at Array.forEach (native)
```

Am I making any obvious mistake here?  I saw https://github.com/LucyBot-Inc/api-spec-converter/issues/122 but in this case my spec has its `basePath` set.

**Comment by bobby-brennan** [comment]
Coming from here: https://github.com/apigee-127/swagger-converter/blob/949a9b724f10bfe3bf44e5f316e390379120c672/index.js#L340

Looks like you've got something weird in one of your types, like an object or an array. Not sure if arrays were allowed in Swagger 1 - if so you can open a bug against `swagger-converter`.

**Comment by bobby-brennan** [comment]
(Also, if it is a bug, reopen this issue and we'll pull in the latest `swagger-converter` when they fix it).

**Comment by ianfixes** [comment]
Will do, and thanks for the quick response!
