### ISSUE TITLE
TypeError: Cannot read property 'description' of undefined

### ISSUE THREAD

**Issue by eonie** [LucyBot-Inc/api-spec-converter#251]
When I convert openapi 3 to swagger_2, I got an error,
```
TypeError: Cannot read property 'description' of undefined
      at forEach (/Users/jiawei/Downloads/oaspaser/node_modules/api-spec-converter/lib/converters/openapi3_to_swagger2.js:226:28)
      at Array.forEach (<anonymous>)
      at module.exports.Converter.convertParameters (/Users/jiawei/Downloads/oaspaser/node_modules/api-spec-converter/lib/converters/openapi3_to_swagger2.js:218:28)
      at module.exports.Converter.convertOperationParameters (/Users/jiawei/Downloads/oaspaser/node_modules/api-spec-converter/lib/converters/openapi3_to_swagger2.js:206:10)
      at module.exports.Converter.convertOperations (/Users/jiawei/Downloads/oaspaser/node_modules/api-spec-converter/lib/converters/openapi3_to_swagger2.js:136:22)
      at module.exports.Converter.convert (/Users/jiawei/Downloads/oaspaser/node_modules/api-spec-converter/lib/converters/openapi3_to_swagger2.js:31:8)
      at converters.swagger_2.Promise.method.oa (/Users/jiawei/Downloads/oaspaser/node_modules/api-spec-converter/lib/formats/openapi_3.js:19:24)
      at tryCatcher (/Users/jiawei/Downloads/oaspaser/node_modules/bluebird/js/release/util.js:16:23)
      at /Users/jiawei/Downloads/oaspaser/node_modules/bluebird/js/release/method.js:15:34
      at Promise.try (/Users/jiawei/Downloads/oaspaser/node_modules/api-spec-converter/lib/base_format.js:165:12)
      at tryCatcher (/Users/jiawei/Downloads/oaspaser/node_modules/bluebird/js/release/util.js:16:23)
      at Function.Promise.attempt.Promise.try (/Users/jiawei/Downloads/oaspaser/node_modules/bluebird/js/release/method.js:39:29)
      at module.exports.BaseFormat.convertTo (/Users/jiawei/Downloads/oaspaser/node_modules/api-spec-converter/lib/base_format.js:157:21)
      at Converter.getSpec.then.fromSpec (/Users/jiawei/Downloads/oaspaser/node_modules/api-spec-converter/index.js:36:32)
      at tryCatcher (/Users/jiawei/Downloads/oaspaser/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/jiawei/Downloads/oaspaser/node_modules/bluebird/js/release/promise.js:547:31)
```
Because some parameters in OpenAPI 3 content does not have `description` property, converter try to get description from parameter's schema properties, but `schema` property also undefind, then converter throw the error.
```
parameters": [
    {
        "name": "username"
    },
    {
        "name": "fullName",
        "description": "fullName"
    },
    {
        "name": "email"
    },
    {
        "name": "phone"
    }
],
```
Here is the source code , which locate in `openapi3_to_swagger2.js`, from line 224.
```
           if (!param.description) {
                const schema = this.resolveReference(this.spec, param.schema);
                if (schema.description) {
                    param.description = schema.description;
                }
            }
```
I thind the `schema` should be checked before use it. I would like to sumit a PR to fix it .

**Comment by rbren** [comment]
Thanks! Happy to accept a PR

**Comment by eonie** [comment]
I saw travis ci build failed  because of test error, but it was passed on my computer.
Do I need push `test/output/swagger_2/common_params.json` to repo?
